spring:
  profiles:
    active:
      - dev

----------------
spring:
  profiles: dev
  application:
    name: mircroservicecloud-config-atguigu-dev

-------------------
spring:
  profiles: test
  application:
    name: mircroservicecloud-config-atguigu-test
